name = "Akash Gurugunti"
avatar = "images/me.jpg" # Avatar image. Default to "images/profile.webp".
bio = "Backend Developement & Cyber Security"
company = "Job Hunting"
location = "Visakhapatnam, India"
# alternatives:
# location = "<a href='https://goo.gl/maps/UWFWsLdCp7AiXvWP7'>Visakhapatnam, India</a>"
# location = "<a href='https://www.google.com/maps/search/Earth'>Earth</a>"
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.

[params]
  # layout = "compact"
