name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when pushing to main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write  # Required for authentication with GitHub Pages

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0     # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Build
        run: hugo --minify

      - name: Adding custom domain redirection
        run: |
          echo "blog.sud0u53r.com" >> ./public/CNAME
          cat ./public/CNAME

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3  # Ensures correct version
        with:
          path: ./public/  # Hugo output directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4  # Deploy using the correct method